### ISSUE TITLE
Issue with relative URLs

### ISSUE THREAD

**Issue by sondr3** [jekyll/jekyll-feed#108]
I just upgraded from 0.4.0 to 0.5.0 and suddenly I get this error: 

```
Liquid Exception: both URI are relative in _includes/head.html, included in _layouts/default.html
jekyll 3.1.2 | Error:  both URI are relative
```

I figured out that it's because you need to have `http://` in front of your URL before, however you didn't need to in 0.4.0. Just curious if this was a intended change.

**Comment by pathawks** [comment]
> I figured out that it's because you need to have http:// in front of your URL before, however you didn't need to in 0.4.0. 

Before what?

How can I reproduce this error? What does your `_includes/head.html` contain?

**Comment by sondr3** [comment]
Sorry, now you need to have your URL include `http://` in front of the URL in `_config.yml` whereas before 0.5.0 you didn't need. All you need to do to reproduce is add `jekyll-feed`, add the feed meta and then have your URL be `url: www.example.com` or `url: http://www.example.com`. Before the new version the first way to write your URL worked.

**Comment by pathawks** [comment]
I have figured it out!

We are [now using 'URI.join' to join `config["url"]` and `config["baseurl"]`](https://github.com/jekyll/jekyll-feed/compare/v0.4.0...v0.5.0#diff-2ca45c54016b64d06027be90e8c00fd6R34) which won't work if neither contains a scheme.

This _shouldn't_ have worked to begin with. If you don't at least include a `//` in the URL, it will not resolve properly.

I agree with you that the error message (`Liquid Exception: both URI are relative`) does not contain enough information to understand how to fix the problem. Maybe a `try catch` with a more helpful warning would make things easier?

**Comment by sondr3** [comment]
Thanks, good to know :)
