### ISSUE TITLE
Stylesheets with XSLT

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-feed#118]
XML supports stylesheets for styling documents using XSLT ([example](http://www.ibm.com/developerworks/xml/tutorials/x-atomxsl/x-atomxsl.html)). Web feeds are usually boring. Let's make them fun again by creating a config option to set a stylesheet `href`!

```xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xml" href="tickertape.xslt.xml"?>
```

**Comment by benbalter** [comment]
@jhabdas that's for opening the idea. I have two questions:

1. How often to users view the feed XML in their browser? What's advantage does a stylesheet provide?

2. What's the advantage to making the XSLT configurable, versus including a default XSLT?

**Comment by jhabdas** [comment]
1) Rarely. But themes like Casper make feeds prominent (upper right of a page) and, as a result, users are more likely to view an unstyled XML feed.

2) The idea of making the XSLT configurable is to allow some to apply creative expression to their web feeds to delight users much the same way 404 pages often get special treatment. A default could be useful as well, but keeping it off means less issues and maintenance for the plug-in.

**Comment by benbalter** [comment]
> A default could be useful as well, but keeping it off means less issues and maintenance for the plug-in.

What if, similar to the feed itself, we wrote a `feed.xslt` file to the site destination, unless it already exists, providing a styled default, but also allowing any user to add their own `feed.xslt` file, without requiring a configuration flag?

**Comment by jhabdas** [comment]
SGTM

**Comment by benbalter** [comment]
@jhabdas if you're able to, any interest in starting a pull request for this? (Even if just to add a default XSLT?)

**Comment by jhabdas** [comment]
On it

**Comment by jhabdas** [comment]
Cloned and tried to run the default rake task after bundling but hit friction building on the version of Ruby Travis is using to run your CI builds. Rather than fighting it (I'm on OS X) or setting up a Docker environment (which would work if one was available) I decided instead to run a quick test using the IBM Ticker Tape XSLT example (linked earlier) against @pathawks Atom feed with the following result:

![screen shot 2016-06-10 at 1 57 33 pm](https://cloud.githubusercontent.com/assets/440298/15975474/4692ee9a-2f13-11e6-8a1d-3914d6e4f927.png)

**Source files used:**

[tickerhawk.zip](https://github.com/jekyll/jekyll-feed/files/309597/tickerhawk.zip)

**Testing:**

Extract above zip to any location, run `python -m SimpleHTTPServer` to start a web server and open `http://localhost:8000/pathawks.xml` to view the transformed file.

**Comment by benbalter** [comment]
> but hit friction building on the version of Ruby Travis is using to run your CI builds

Do you have a link/PR? Glad to take a look.

**Comment by jhabdas** [comment]
@benbalter Added a basic example in #119 for you to try. Can't do much else until I can get my environment working, unfortunately.

**Comment by benbalter** [comment]
> until I can get my environment working, unfortunately.

How are you running the tests? What version of Ruby are you running? It should work with any version greater than 2.0.

**Comment by jhabdas** [comment]
It's not you, it's me. 😅   FWIW here's [the issue I'm running up against](https://github.com/ffi/ffi/issues/461). I've already tried several workarounds and versions of Ruby. If you have any experience with this particular error on OS X please LMK though it's probably a red herring.

**Comment by jhabdas** [comment]
@benbalter I was able to [workaround my environment issues](https://github.com/ffi/ffi/issues/461#issuecomment-225450909) and updated #119 to allow generation of the stylesheet if one does not already exist. Mind taking a look and let me know your thoughts on implementation and any immediate thoughts on basic feed styling?
