### ISSUE TITLE
Add ability to modify permalink

### ISSUE THREAD

**Issue by cmegown** [jekyll/jekyll-feed#122]
It would be nice to be able to specify a desired permalink (ex: `/feed/`) instead of the default `/feed.xml`. I'm not sure how this would work out with a permalink structure defined in `config.yml`, but it would probably have to play nicely with that as well.

**Comment by benbalter** [comment]
You can! See https://github.com/jekyll/jekyll-feed#already-have-a-feed-path.

**Comment by cmegown** [comment]
Well I _did_ see that but you aren't able to specify something like `/feed/` and receive the desired result. Doing so built a `feed` directory, but inside was an `index` file (note: no `.html` file extension).

Here's what's in my config:

```
gems:
    - jekyll-feed

feed:
    path: /feed/
```

**Comment by benbalter** [comment]
Have you tried?

```yml
feed:
  path: /feed/index.xml
```

**Comment by cmegown** [comment]
Hmm interesting. `/feed/index.xml` does indeed output correctly. For some reason I wasn't thinking and was trying `/feed/index.html`, but that incorrectly outputs `feed > index > index.html`.

I'm not sure if that qualifies as a bug or not, but at the very least the documentation could be clarified a bit.
