### ISSUE TITLE
Feed not generating, `feed_meta` not available

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll-feed#123]
Not really sure what's going on, but this doesn't seem to be working at all.

Here's some info about my setup:

```
MHVA74DRVG:www troy4461$ bundle list
Gems included by the bundle:
  * bundler (1.11.2)
  * colorator (0.1)
  * ffi (1.9.10)
  * jekyll (3.1.6)
  * jekyll-feed (0.6.0)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (1.4.0)
  * jekyll-watch (1.4.0)
  * kramdown (1.11.1)
  * liquid (3.0.6)
  * listen (3.0.8)
  * mercenary (0.3.6)
  * posix-spawn (0.3.11)
  * pygments.rb (0.6.3)
  * rb-fsevent (0.9.7)
  * rb-inotify (0.9.7)
  * redcarpet (3.3.4)
  * rouge (1.11.1)
  * safe_yaml (1.0.4)
  * sass (3.4.22)
  * yajl-ruby (1.2.1)
```

```
MHVA74DRVG:www troy4461$ cat Gemfile
source 'https://rubygems.org'
gem 'jekyll', '~> 3.0'
gem 'redcarpet', '~> 3.3', '>= 3.3.3'
gem 'pygments.rb', '~> 0.6.3'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-feed'
```

```
MHVA74DRVG:www troy4461$ cat _config.yml 
gems:
  - jekyll-feed
```

```
MHVA74DRVG:www troy4461$ bundle exec jekyll doctor
Configuration file: /www/_config.yml
  Your test results are in. Everything looks fine.
```

```
MHVA74DRVG:www troy4461$ bundle exec jekyll b
Configuration file: /www/_config.yml
            Source: /www
       Destination: /www/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 5): Unknown tag 'feed_meta' in _includes/head.html, included in _layouts/default.html
jekyll 3.1.6 | Error:  Liquid syntax error (line 5): Unknown tag 'feed_meta'
```

Any ideas?

**Comment by parkr** [comment]
👋  @troyswanson! Long time, no talk! Hope all is well with you.

This looks like jekyll isn't loading it. When you run `bundle exec jekyll build --verbose`, do you see `Requiring: jekyll-feed` toward the top? If not, could it be that safe mode is enabled in your configuration file? Let me know 😄

**Comment by troyswanson** [comment]
👋  Hi @parkr! Miss you, brother. Checking right now, sir.

**Comment by troyswanson** [comment]
Hmm, doesn't look like it's appearing.

```
MHVA74DRVG:www troy4461$ bundle exec jekyll build --verbose | grep jekyll-feed
  Liquid Exception: Liquid syntax error (line 5): Unknown tag 'feed_meta' in _includes/head.html, included in _layouts/default.html
```

Safe mode isn't anywhere in my config file.

**Comment by parkr** [comment]
Oh, weird! Did you notice anything interesting in your `_config.yml`? A stray space somewhere? What is the output of `ruby -rsafe_yaml -e "p SafeYAML.load_file('_config.yml')"`?

**Comment by parkr** [comment]
Have any plugins in `_plugins`, too?

**Comment by troyswanson** [comment]
Well, I'm a bad and dumb.

I had the `gems` property defined later down in my config file, which overwrote the one that had `jekyll-feed` in it. Sorry for the bother!

**Comment by parkr** [comment]
@troyswanson No problem at all! Maybe that could be a Jekyll doctor check? Not sure if SafeYAML has a means of reporting this, but it would save some headaches. 😄

**Comment by troyswanson** [comment]
Unsure. Could just be a simple matter of adding a little "Troubleshooting" section in the README.
