### ISSUE TITLE
Invalid title tag with respect to RFC

### ISSUE THREAD

**Issue by k0ral** [jekyll/jekyll-feed#125]
The generated Atom feed does not seem to respect [section 3.1.1.1 from RFC4287][1]:

> Example atom:title with text content:
> 
> 
> ```
> ...
> <title type="text">
>   Less: &lt;
> </title>
> ...
> ```
> 
> If the value is "text", the content of the Text construct MUST NOT contain child elements.

[Here][2] is an example. The `title` tag claims to be pure text, but includes children tags. I believe either the title should have been marked "xhtml", or escape sequences should have been used to avoid misinterpretation of the text content.

Note: I'm not using jekyll myself, I just noticed this issue while subscribing to the atom feed from the mentioned jekyll blog.

[1]: https://tools.ietf.org/html/rfc4287#section-3.1.1.1
[2]: http://degoes.net/feed.xml

**Comment by pathawks** [comment]
You are correct. I believe this is a duplicate (or at least very much related to) #98.

Closing this issue to keep the conversation over there, but this is definitely something we need to figure out.

**Comment by pathawks** [comment]
The example feed provided is not generated by this plugin.

**Comment by k0ral** [comment]
Would you know where I should report this issue then ? It is linked to jekyll somehow, according to the following tag:

```xml
<generator uri="https://github.com/mojombo/jekyll">Jekyll</generator>
```

**Comment by pathawks** [comment]
@k0ral You will have to contact the site owner directly. I have no doubt the site is using Jekyll, but it is not using this plugin.
