### ISSUE TITLE
Request: Default Post Image

### ISSUE THREAD

**Issue by shellscape** [jekyll/jekyll-feed#126]
I'd like to request the ability to configure a default image in `_config.yml` for a post when none has been defined in the post's frontmatter.

**Comment by benbalter** [comment]
@shellscape have you tried using [front matter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults) to acomplish this?

**Comment by shellscape** [comment]
@benbalter learning new jekyll magic all the time, thanks for that. I think it'll allow me to accomplish what I was after!
