### ISSUE TITLE
Draft articles disappear on regeneration with jekyll-feed enabled

### ISSUE THREAD

**Issue by artlogic** [jekyll/jekyll-feed#135]
Steps to reproduce:
1. Start a new Jekyll site with 3.2.1
2. Install and enable jekyll-feed
3. Create a draft post in _drafts
4. Serve the site with: `jekyll s --drafts`
5. Notice that your draft is listed on the front page.
6. Edit your draft. The site should regenerate.
7. Your draft is no longer listed.

This does not happen with non drafts. Additionally, if you edit some other file (like a post) the draft will reappear on site regeneration. Only the most recently edited draft disappears.

**Comment by artlogic** [comment]
The problem seems to stem from this line of code: `@site.config["time"] = Time.new`
(ref: https://github.com/jekyll/jekyll-feed/blob/v0.7.1/lib/jekyll/jekyll-feed.rb#L11)

When Jekyll runs `site.reset`, it either uses the time set in `config["time"]` or sets the `self.time = Time.now`. Because drafts use the file modified time as the publish time, when I regenerate, the `site.time` is stuck at the first time the feed plugin was run, and suddenly that post is in the future and does not display.

What's the purpose of `@site.config["time"] = Time.new`? It's not immediately obvious to me.

**Comment by pathawks** [comment]
Does this only happen when **jekyll-feed** is installed? I don't see how it could be related.

**Comment by artlogic** [comment]
Yes. It's caused by `@site.config["time"] = Time.new`. If I comment that line, it works as expected. What is the purpose of that line of code?

**Comment by pathawks** [comment]
[In the feed template, we need to know the current time.](https://github.com/jekyll/jekyll-feed/blob/v0.7.1/lib/feed.xml#L12)

There may be a better way for us to do this, such that it won't interfere with anything else in the build. I will take a look :+1:

**Comment by parkr** [comment]
@pathawks Jekyll already [sets `site.time`](https://github.com/jekyll/jekyll/blob/a920cf040b3ebbbca1b3ee4b6868dd6642b2ee85/lib/jekyll/site.rb#L85-L89). No need to set it again, right?

**Comment by artlogic** [comment]
FYI - If this is determined to be unnecessary, [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap/blob/v0.11.0/lib/jekyll/jekyll-sitemap.rb#L11) has the same line of code. I'd be happy to open an issue in that repo as well, if needed.

**Comment by pathawks** [comment]
Trying to get to the bottom of why it is there.
It has been part of [**jekyll-feed** since the initial commit](https://github.com/jekyll/jekyll-feed/blob/2fc55785169492b8ea1cf2d534a1af7c167ebe0f/lib/jekyll-rss-feed.rb#L17), I imagine because the scaffolding was copied from **jekyll-sitemap**.

In **jekyll-sitemap** that line has been there [since v0.1.0](https://github.com/jekyll/jekyll-sitemap/commit/21619f98e1fdac98d36d5ac41ee52a4645f6a90e#diff-c5defd0871f3852c203d312fdb710f67R11).

If we remove this, does the plugin break on older versions of **Jekyll**? Does anything even change?

**Comment by artlogic** [comment]
I did a little digging. It looks like Jekyll has been setting `site.time` to current since v0.6.0: https://github.com/jekyll/jekyll/blob/v0.6.0/lib/jekyll/site.rb#L31

**Comment by pathawks** [comment]
I don't know if this plugin still supports Jekyll v0.6.0 or not. I would love to require Jekyll v3.3.0 as soon as GitHub pages supports it, but in the meantime I am very cautious about breaking anything.

So, would you mind checking out 18b2c0baa7b53625f86bd62d57ff3514674609e3 and confirming that this fixes the issue for you? In a future release we can get rid of that line entirely, but for now maybe we can settle for only setting it once and only if it hasn't yet been set.

**Comment by pathawks** [comment]
All of that said, if the feed is regenerated, wouldn't you _expect_ it to reflect that in the `<updated>` element?

**Comment by artlogic** [comment]
The problem remains.

The real issue here is that `@site.config["time"]` appears to be very different from `site.time`. From the docs, `site.time` is: "The current time (when you run the jekyll command)." Whereas `@site.config["time"]` seems to be used to *override* `site.time`. While the code seems to have changed throughout various Jekyll releases, it's always been something like this:

```ruby
if config["time"]
  self.time = Utils.parse_date(config["time"].to_s, "Invalid time in _config.yml.")
else
  self.time = Time.now
end
```

By setting `@site.config["time"]`, the plugin is actually telling the site to override the default behavior of using the current time as `site.time` and instead use the time of last regeneration as `site.time`. I can't see how this could be anything but a bug.

Another place where this crops up in in feed times. Here's how you can see the problem:
1. Run `jekyll s` on a site with the *jeykll-feed* enabled.
2. Note the feed's last updated time. It's the current time.
3. Edit a post, causing the site to regenerate.
4. Notice that the feed's last updated is not set to the current time, but the time the site was last generated.

**Comment by pathawks** [comment]
Did you checkout and test against 18b2c0baa7b53625f86bd62d57ff3514674609e3? _It_ should not be setting `site.time` ever at all on recent versions of Jekyll.

It seems to be working for me, but I want to make sure it solves your specific problem.

**Comment by artlogic** [comment]
Yes. I've run quite a few tests against https://github.com/jekyll/jekyll-feed/commit/18b2c0baa7b53625f86bd62d57ff3514674609e3.

In essence, if I run `jekyll s --drafts` at 3:00PM, and make changes until 3:30PM, my site still thinks it's 3:00PM, because jekyll-feed has overridden `site.time` by setting `site.config["time"]` initially.

I'd urge you to review [`site.reset`](https://github.com/jekyll/jekyll/blob/v3.2.1/lib/jekyll/site.rb#L84). You'll see that since v0.6.0, setting `site.config["time"]` has had the effect of overriding `site.time`.

**Comment by pathawks** [comment]
Oh. Yeah, I see.

Well, I guess the other option is to wait until Jekyll v3.3.0 ships and drop support for all older versions of Jekyll so we can delete that line all together.

**Comment by artlogic** [comment]
It seems that @parkr added the line to sitemaps (https://github.com/jekyll/jekyll-sitemap/commit/21619f98e1fdac98d36d5ac41ee52a4645f6a90e). Maybe he understands the purpose?

The only possible value I can see is that if someone has set `time` in `_config.yml`, this line will cause the feed to be generated with the current time, rather than the time set in `_config.yml`. Could that have been the intention?

If so, would this be an acceptable fix?

```ruby
if @site.config["time"]
  @site.config["time"] = Time.new
end
```

**Comment by pathawks** [comment]
I'm pretty sure **jekyll-feed* doesn't actually support anything earlier than Jekyll v3.1.0 anyway, due to our use of the `smartify` filter.

**Comment by artlogic** [comment]
@pathawks Are you feeling like the only option is waiting for Jekyll 3.3? Do you think my proposed change is to too much? I'd really like to see this fixed, but if it needs to wait, I'd just like to get an idea of when it might get fixed.

**Comment by pathawks** [comment]
Without really understanding _why_ this is there, I am reluctant to mess with it.

I would rather just remove it all together and drop support for super old versions of Jekyll. If we're soon going to be dropping support for anything older than v3.3.0, may as well do it all at once.

If you enable `future_posts` does the problem go away?

**Comment by artlogic** [comment]
Yes - that is a good temporary work around. Do you need me to submit pull requests for this and **jekyll-sitemap**? It looks like v3.3.0 will be out fairly soon.

**Comment by pathawks** [comment]
If you'd like to open a PR to rip that line out, I'd be cool with that :+1:

**Comment by artlogic** [comment]
Done - see: https://github.com/jekyll/jekyll-feed/pull/138

**Comment by artlogic** [comment]
Thanks for your help with this @pathawks!
