### ISSUE TITLE
Add support for `image` element

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-feed#14]
Example:  https://github.com/mpc-hc/mpc-hc.org/blob/master/source/rss.xml#L22-L29

https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements

**Comment by pathawks** [comment]
Yes, love it. *But* we would need to make sure that such an image actually exists in the site first.

Is there a way to do this without just config :christmas_tree:?

Also, perhaps #2 should be sorted out first, before diving too deep into these features?

**Comment by XhmikosR** [comment]
I don't think you can do that since the URL is the remote one.

Since this is an optional element, I'd say whoever is using it knows what to do with it :P

What I think we could have is a check for the dimensions since the specs have a limit there.

**Comment by pathawks** [comment]
> I don't think you can do that since the URL is the remote one.

I just mean we shouldn't start including an `<image>` in all sitemaps; there would need to be either a setting or something to specify the image URL, or a check for a specific file to be used as the image if it existed.

**Comment by XhmikosR** [comment]
Oh, that. Sure.

But IMO all image sub-elements should be mandatory so we should check for all of them.

**Comment by pathawks** [comment]
In [Atom, this are called](http://atomenabled.org/developers/syndication/#optionalFeedElements) `<logo>`, and there is also `<icon>` for favicon type images.

(Just leaving notes for myself.)

**Comment by ElMassimo** [comment]
Any updates on this one?

**Comment by XhmikosR** [comment]
That is a post image though. Not a site wide one. Does atom support image
in root?

**Comment by pathawks** [comment]
@XhmikosR Do you know of a feed reader that displays a per feed image? How would this be used?

**Comment by XhmikosR** [comment]
I know Firefox shows the image to the right. But that was with RSS. Not sure if atom supports it. The original request was from when this repo was RSS.

**Comment by pathawks** [comment]
FWIW, WordPress adds a [square 32px icon](https://github.com/WordPress/WordPress/blob/a5d44337b204539cd59c029ca1e39d08a4d10e30/wp-includes/feed.php#L561-L573) to Atom feeds.

I am not sure what this would be used for and I can't think of any way to add support for it without adding a config option (:christmas_tree:), so I am not enthusiastic about the idea.

**Comment by XhmikosR** [comment]
A config option will be needed that for sure.

I just feel an image makes things more official in a feed. It's the only thing I miss from my old RSS custom solution I was using.

**Comment by inetbiz** [comment]
Is this implemented yet?
