### ISSUE TITLE
Can't see collections except site.posts

### ISSUE THREAD

**Issue by CodeMaxx** [jekyll/jekyll-feed#142]
I have another folder by the name of `site.extras` whose feed is not shown by `feed.xml`. How do I make this work?

**Comment by pathawks** [comment]
Duplicate of #124

**Comment by CodeMaxx** [comment]
@pathawks Its not a duplicate.  I don't want separate feeds for them, it would work even if they are in one file. I had already seen that issue before opening this one.

**Comment by pathawks** [comment]
I guess the bottom line is that, right now, the plugin _only_ supports posts. We do not support other collections, in the same feed or in a different feed.

**Comment by CodeMaxx** [comment]
Oh right, are you guys planning on working on this? I think this is a major feature requirement

**Comment by pathawks** [comment]
I would be happy to review a pull request:+1:
