### ISSUE TITLE
Feeds must contain <author> to validate

### ISSUE THREAD

**Issue by dret** [jekyll/jekyll-feed#146]
as reported in https://github.com/jekyll/minima/issues/89:
* the generated feed is broken. https://validator.w3.org/feed reports a missing author element and other problems.
* also, it seems that feed.xml gets served as `application/xhtml+xml` but it should be `application/atom+xml`

**Comment by pathawks** [comment]
We don't control the content type of the feed; that's an issue with your server configuration.

Can you be more specific about what you mean when you say the “feed is broken?” As discussed in #144, the generated feed does validate.

**Comment by dret** [comment]
On 2016-11-29 16:25, Pat Hawks wrote:
> We don't control the content type of the feed; that's an issue with your
> server configuration.

that's too bad. is there any way jekyll can define the content type of a 
resource? if not, i guess this one is hard to fix.

> Can you be more specific about what you mean when you say the “feed is
> broken?” As discussed in #144
> <https://github.com/jekyll/jekyll-feed/issues/144>, the generated feed
> does validate.

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2F2017.ws-rest.org%2Ffeed.xml 
is the example i am looking at. it is this odd constraint of atom that 
there must always be an author element.

**Comment by pathawks** [comment]
If a site author is specified, we will include it.
If not, should we output an empty `<author>` element?

**Comment by dret** [comment]
On 2016-11-29 21:21, Pat Hawks wrote:
> If a site author is specified, we will include it.
> If not, should we output an empty |<author>| element?

technically speaking, atom requires each entry to have an author, 
directly or inherited. so for each entry either the entry must have an 
author, or the feed (if both then entry overrides author). if neither 
one does, then in order to at least satisfy the syntax requirements, an 
empty author element probably is the best idea.
