### ISSUE TITLE
the generated Feed XML parse error

### ISSUE THREAD

**Issue by zixia** [jekyll/jekyll-feed#147]
I had a new blog at here: https://blog.wechaty.io/ , and generated the feed XML file at here: https://blog.wechaty.io/feed.xml

But the feed.XML file got a parse error in both chrome and safari.

The link is here: https://blog.wechaty.io/feed.xml , I believe there's must some special character in my blog post which caused the generate program not work as expected.

**Comment by pathawks** [comment]
You are just missing `<author>` information.

Duplicate of #146

**Comment by zixia** [comment]
@pathawks Thanks!
