### ISSUE TITLE
Only add xml-stylesheet if provided

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-feed#148]
**jekyll-sitemap** will only link to a stylesheet if one is provided; it does not provide its own default stylesheet.

I like this approach. I don't particularly care how my feed renders in a web browser, but if it is going to be skinned it seems like it should be skinned to fit the site. We should encourage themes to provide a stylesheet, but I don't know that we need to provide one by default.

jekyll/jekyll-sitemap#143

**Comment by benbalter** [comment]
> We should encourage themes to provide a stylesheet, but I don't know that we need to provide one by default.

👍 to this approach. FWIW, the existing stylesheet makes it hard to debug feed issues and compare unrendered feeds.

**Comment by ashmaroli** [comment]
> We should encourage themes to provide a stylesheet

Hi guys, say Minima is able to deploy a stylesheet (e.g. `feed.xslt.xml`) for this. How would a user be able to enable / disable it (if they do not want to use `Jekyll Feed` or generate feeds at all, the XSL file shouldn't exist in their `_site`)

**Comment by pathawks** [comment]
@ashmaroli I understand where you are coming from, but I don't think it's a problem for themes to just always provide an XSLT by default.

If a user only uses certain social media icons, it's not like the other images are excluded from the generated site.

**Comment by ashmaroli** [comment]
I see..
Would the presence of `feed.xslt.xml` affect a `feed.xml` generated without using `jekyll-feed`?

**Comment by pathawks** [comment]
Only if that feed explicitly linked to the XSLT.
