### ISSUE TITLE
Allow specifying the language code

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-feed#15]
By default, don't add anything, but give the user the ability to specify the language code.

**Comment by pathawks** [comment]
Is there any prior art here?

Do any of the importers import any language information, either per post or per site?

Is there any existing convention for specifying this information?

**Comment by XhmikosR** [comment]
Only the specs as far as I can tell. `language` is a per site element.

**Comment by pathawks** [comment]
But, because it XML, any element can have an `xml:lang` attribute.

**Comment by XhmikosR** [comment]
That is true, but the specs don't mention anything about each element. So it should be a per channel sub-element.

**Comment by pathawks** [comment]
Is there any prior art here at all? Are there any **i18n** Jekyll plugins/workflows that set language information anywhere?

**Comment by parkr** [comment]
> Are there any i18n Jekyll plugins/workflows that set language information anywhere?

@pathawks There are a number of i18n plugins for Jekyll out in the wild. Octopress's Multilingual is the only one whose development I have followed. https://github.com/octopress/multilingual

**Comment by pathawks** [comment]
I don't see any `language` element in the Atom spec, but `<feed>` could have an `xml:lang` set to `{{ site.lang }}`, if present. Each `<entry>` could also have an `xml:lang` set to `{{ post.lang }}`. All links could also include `hreflang` if we can reasonably figure out the language of the resource the link points to.

Would this be reasonable/sufficient? Are there any great examples of feeds from multilingual sites that properly include language information to look to as an example?

**Comment by pathawks** [comment]
This has been fixed by #75

**Comment by XhmikosR** [comment]
Thanks! Any chance for a new release?
