### ISSUE TITLE
(Question) Any way to add a post permalink to the bottom of each feed entry?

### ISSUE THREAD

**Issue by alecsatin** [jekyll/jekyll-feed#157]
Is there any way to automatically add a post permalink to the bottom of each RSS entry?  This helps in the identification of RSS "content scrapers".  

I tried adding code to the "single" layout.  It shows up on the post, but not in the feed.

Thanks for the plugin, and for any help or suggestions.
Alec

**Comment by pathawks** [comment]
No, currently there is no way to add something like this to the feed template.
