### ISSUE TITLE
Double // in feed.xml for site <id>

### ISSUE THREAD

**Issue by mmistakes** [jekyll/jekyll-feed#158]
## Steps to reproduce

1. `jekyll new test-site`
2. Add `url: http://test-site.com` to _config.yml
3. Build site.
4. Examine `_site/feed.xml` 

```xml
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xml" href="/feed.xslt.xml"?>
  <feed xmlns="http://www.w3.org/2005/Atom">
    <generator uri="http://jekyllrb.com" version="3.4.0">Jekyll</generator>
    <link href="http://test-site.com/" rel="alternate" type="text/html" />
    <updated>2017-02-16T12:27:08-05:00</updated>
    <id>http://test-site.com//</id>
    <title type="html">Your awesome title</title>
    ...
```

This line in [`feed.xml`](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml#L10) seems to be the culprit and outputs `//` for site root. Perhaps the combination of the new `absolute_url` `xml_escape` filters is causing it as the `link` line above doesn't seem to have this problem.

```html
<id>{{ '/' | absolute_url | xml_escape }}/</id>
```

## Expected Result

```xml
<id>http://test-site.com/</id>
```

**Comment by pathawks** [comment]
This is a problem with the `absolute_url` filter in Jekyll.
jekyll/jekyll#5541

**Comment by pathawks** [comment]
Hmm.

This doesn't happen in the `<link>` tag; only in the `<id>` tag. Difference is the `xml_escape` filter.

**Comment by mmistakes** [comment]
@pathawks I noticed that too. Really strange.

**Comment by pathawks** [comment]
There's a trailing slash _after_ the Liquid. I am banging my head against a wall right now.

https://github.com/jekyll/jekyll-feed/blob/v0.8.0/lib/feed.xml#L8

**Comment by mmistakes** [comment]
Hahah. It's crazy how that extra `/` just blended in. Completely missed that!
