### ISSUE TITLE
Add a shell script to validate xml files with CI

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-feed#163]
We could catch bugs in the generated markup if a script was written to have `xmllint` validate the generated xml files in various situations, with Travis CI.

Thoughts?

**Comment by pathawks** [comment]
Not a shell script, but we should probably use Nokogiri instead of just regex in our test suite :+1:

**Comment by ashmaroli** [comment]
Nokogiri is great too.. :smiley:  :+1:

**Comment by pathawks** [comment]
Wait... we [have this already](https://github.com/jekyll/jekyll-feed/blob/v0.9.1/spec/jekyll-feed_spec.rb#L100-L107)

**Comment by ashmaroli** [comment]
its not a full-blown validation though..

**Comment by pathawks** [comment]
It is [validated by the W3 validation service](https://github.com/jekyll/jekyll-feed/blob/v0.9.1/spec/jekyll-feed_spec.rb#L178-L206)

**Comment by ashmaroli** [comment]
yet.. we still encountered a bug in the generated feed..
okay, closing this.

**Comment by pathawks** [comment]
We weren't testing for cases where `site.lang` was set.
