### ISSUE TITLE
Respect Base URL when for Alternate and Self

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-feed#171]
I could be off base here, but I didn't see a test covering it and [these lines](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml#L8-L10) looked a little fishy to me:

```
<link href="{{ '/' | absolute_url }}" rel="alternate" type="text/html" {% if site.lang %}hreflang="{{ site.lang }}" {% endif %}/>
<id>{{ '/' | absolute_url | xml_escape }}</id>
```

My mental parser says these will produce an unexpected result when `baseurl` is set. Sorry for not creating an actual test case. I'm not familiar with any sites offhand using subdirs.

**Comment by benbalter** [comment]
What would be the unexpected result?

**Comment by jhabdas** [comment]
Never mind. I'm an idiot. Sorry for the noise. I was thinking the filter would for some reason _omit_ the `baseurl`, but obviously that's not going to happen when it's part of the URL itself. 🤦‍♂️
