### ISSUE TITLE
Renders more than the 10 most recent posts.

### ISSUE THREAD

**Issue by speedcom** [jekyll/jekyll-feed#174]
Is it possible to set some option and exceed that number so that more feeds is generated in feed.xml file?

**Comment by benbalter** [comment]
See https://github.com/jekyll/jekyll-feed/pull/107 and https://github.com/jekyll/jekyll-feed/issues/56.

**Comment by speedcom** [comment]
If I'm correctly thinking according to both discussions this is simply NOT possible at current form?
Otherwise, is there any way to overcome this? Its a showstopper to me.

**Comment by benbalter** [comment]
Correct, it's not possible. Why is it a showstopper for you?

**Comment by jhabdas** [comment]
FWIW it's good this is limited by default and without option, otherwise someone _might_ get clever and point a spider at github and aggregate the content of all the public jekyll sites on it.
