### ISSUE TITLE
Url from _config not appearing in my feed

### ISSUE THREAD

**Issue by jennifert** [jekyll/jekyll-feed#175]
Hello,

Unfortunately, the output for my feed keeps outputting "localhost:4000" as seen here: [https://jenntesolin.com/atom.xml](https://jenntesolin.com/atom.xml). 

I tried playing around with "url" and "baseurl", but so far, no luck. Attached is my current config file - am I missing something?

![screen shot 2017-05-28 at 3 03 16 pm](https://cloud.githubusercontent.com/assets/3802757/26531426/dff2386c-43b6-11e7-85fe-e544c116d856.png)

**Comment by mmistakes** [comment]
Run `jekyll build` instead. `jekyll serve` overrides `url` values with `http://localhost:4000` when running a development server locally.

**Comment by jennifert** [comment]
Wow. Thanks. Will need to fix my build script.

**Comment by samaitra** [comment]
@jennifert @mmistakes thank you for sharing the issue and solution, helped me a lot
