### ISSUE TITLE
Output XHTML in Feeds

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-feed#179]
It's my understanding one of the perceived disadvantages with RSS 2.0 was payload encoding of ampersands (`&`) and angle brackets (`<`|`>`) in structured content and that that shortcoming was addressed in the design of Atom 1.0.

According to [payload comparisons](http://www.intertwingly.net/wiki/pie/Rss20AndAtom10Compared) in the Atom Wiki an advantage of Atom is the ability to use well-structure XHTML within feeds (as well as other XML vocabs).

Is there a particular reason Atom [`html` text construct](https://tools.ietf.org/html/rfc4287#section-3.1) is being used in Jekyll Feed as opposed to `xhtml`? It seems using XHTML would enable use of `<` and `&` within content and therefore making feeds more human readable and easier to operate on programmatically.

**Comment by pathawks** [comment]
That would only work if we could be sure that the content was valid XHTML, otherwise would result in broken feeds.

**Comment by jhabdas** [comment]
Thanks again, Pat. I will keep it in consideration. A very interesting feature no doubt.

**Comment by pathawks** [comment]
I would love it if this were possible.

**Comment by jhabdas** [comment]
I just ran a vaildator against a single JSON `entry` element with the Atom NS and raw HTML output with the XHTML NS embedded. I'll leave this open as a possible exploration. I can't personally put any time into it but I'd like to see it to. There's some very real value here IMHO.

**Comment by pathawks** [comment]
Problem is that we have no control over what users give us as post content. If they have a mistake in their HTML, or even if they are writing HTML-style-HTML instead of XHTML-style-HTML (which -- I must remind myself -- is a perfectly valid option), the whole feed will fail to validate.

I don't see this plugin supporting this; I think the risks clearly outweigh the benefits.

**Comment by jhabdas** [comment]
That makes sense. Thanks for clarifying. I was thinking the markup passed in [could be converted](https://github.com/jfisteus/html2xhtml) from HTML to XHTML but seems like that might make more sense in a fork. Appreciate the info.

**Comment by pathawks** [comment]
> I was thinking the markup passed in could be converted from HTML to XHTML

This would have to be 100% perfect. If the conversion made anything render differently in XHTML than how it rendered in HTML we would be violating user expectations.

**Comment by jhabdas** [comment]
Yeah, makes sense. Seems like like another task for a future revision of the Atom spec. Given HTML5 put the onus on browsers to handle whatever was throw at them seems like what should be done to eliminate the weird conversion step would be to improve the spec or simply drop HTML5 into CDATA.
