### ISSUE TITLE
Some posts be added to feed.xml file But Others not be added. How Can I solve?

### ISSUE THREAD

**Issue by YuTaeseong** [jekyll/jekyll-feed#180]
I use jekyll-feed.
and include {% feed_meta %} in <head>.
But Some posts be added to feed.xml file But Others not be added.

* I am Korean user

**Comment by pathawks** [comment]
Only the most recent 10 posts are added to the feed.

Which posts is your feed missing?

**Comment by YuTaeseong** [comment]
oh I got it. thanks. I've posted over 10 posts
