### ISSUE TITLE
/feed.xml created in development and not production

### ISSUE THREAD

**Issue by Khanthulhu** [jekyll/jekyll-feed#183]
When you click the RSS link on any of the index pages (www.johnbrock.io) you get a 404 error but when you click the link in development the feed works fine.

Source code is here https://github.com/Khanthulhu/JohnBrock

**Comment by benbalter** [comment]
@Khanthulhu I can't speak to the specifics of your local set up. If you [contact GitHub support](https://github.com/contact) they should be able to help you get things straightened out.

**Comment by Khanthulhu** [comment]
I contacted github support. The problem was caused by my config file using 'plugins' instead of 'gems'.

**Comment by Khanthulhu** [comment]
The problem was caused by my config file using 'plugins' instead of 'gems'.
