### ISSUE TITLE
Use absolute path for images in post.content

### ISSUE THREAD

**Issue by dtsn** [jekyll/jekyll-feed#185]
When you reference an image using a relative URL (e.g. /uploads/image1.jpg) in lots of common feed readers these aren't visible. Ideally, they need to be absolute URL's. I currently do this as a manual process however, we can perform a simple replace in the `post.content` to add the `site.url` to the beginning.

**Comment by benbalter** [comment]
> need to be converted to absolute URL's

Can you explain why they need to be converted?

**Comment by dtsn** [comment]
When you view the feed using a feed reader they can't load up the images.

**Comment by benbalter** [comment]
We set [the `xml:base` property](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml#L42), which should make rewriting the URLs themselves uncecesary. 

Via [the atom spec](https://tools.ietf.org/html/rfc4287):

>    Any element defined by this specification MAY have an xml:base
   attribute [W3C.REC-xmlbase-20010627].  When xml:base is used in an
   Atom Document, it serves the function described in section 5.1.1 of
   [RFC3986], establishing the base URI (or IRI) for resolving any
   relative references found within the effective scope of the xml:base
   attribute.

**Comment by dtsn** [comment]
Thanks! It may just be my terrible RSS reader, i'll investigate some others.
