### ISSUE TITLE
Also include pages in feed.

### ISSUE THREAD

**Issue by weakish** [jekyll/jekyll-feed#186]
Currently pages are excluded in feed.

**Comment by benbalter** [comment]
Thanks for this. Do you mind providing a bit more information about what problem you're trying to solve?

**Comment by weakish** [comment]
> what problem

jekyll-feed does not include pages in generated rss feed.

**Comment by parkr** [comment]
@weakish Why do you need Pages in your feed? Pages are not feed-able because they have no clear collective coherence of content & they don't have dates. If you have either of those qualities, then you should be using [Collections](https://jekyllrb.com/docs/collections/) instead.
