### ISSUE TITLE
Feed Limit?

### ISSUE THREAD

**Issue by bsullins** [jekyll/jekyll-feed#192]
Is there an option to specify the number of entries the feed should contain? I'm looking to generate a feed with 50 entries but currently, it only has a few listed.

Thanks,
Ben

**Comment by pathawks** [comment]
See #40 and #56 for some prior discussion regarding this matter.

**Comment by pathawks** [comment]
> Is there an option to specify the number of entries the feed should contain?

Sorry, I didn't answer the question. No, currently there is no such option.

**Comment by bsullins** [comment]
thanks for the reply. Down the rabbit hole I go...
