### ISSUE TITLE
pre/code tags in feed are loosing the newlinines

### ISSUE THREAD

**Issue by fabsenet** [jekyll/jekyll-feed#196]
Hi, I searched around, could not find any still open relevant issue for this, so here i go:

I have a page with a feed, the post contains multiline-code with newlines, the feed has still the code tag but all is in one paragraph now without newlines! I am not sure, what is wrong. My blog is not really far off from the jekyll default+minima?

the blog source is at https://github.com/fabsenet/blog_de
the blog runs at https://fabse.net
the feed is at https://fabse.net/feed.xml
A good example is the latest post, search for "isLedOn" (it is contained in this post: [rendered](https://fabse.net/raspberry-pi-diy/02-LED-Blinken-lassen/#das-vollst%C3%A4ndige-programm) / [markdown](https://github.com/fabsenet/blog_de/blob/master/_posts/2017-10-23-02-LED-Blinken-lassen.md#das-vollst%C3%A4ndige-programm))

I am not sure, maybe I configured something wrong? But all I know is, the end result is wrong.

Can you guys give me a hint?

**Comment by pathawks** [comment]
We do minify the feed template, but that shouldn't affect the content that goes inside that template.

https://github.com/jekyll/jekyll-feed/blob/f879ed22076fce4cff98b22fec7d0ec85f9a3199/lib/jekyll-feed/generator.rb#L49

The template itself uses the `strip` filter, which should remove leading and trailing whitespace, but should not affect whitespace inside the content.

https://github.com/jekyll/jekyll-feed/blob/f879ed22076fce4cff98b22fec7d0ec85f9a3199/lib/jekyll-feed/feed.xml#L42

I'm not sure. I suppose the thing to do is to create a failing test and see if we can get to the bottom of what is stripping those spaces.

**Comment by pathawks** [comment]
@fabsenet I don't think this is anything that you have done wrong. Seems like a problem with the plugin.

**Comment by pathawks** [comment]
Hmm... we already do have a test for this.

https://github.com/jekyll/jekyll-feed/blob/10071c56678a5bb3ccff8806334fb750b6baf716/spec/jekyll-feed_spec.rb#L57-L59

**Comment by pathawks** [comment]
The problem is the [**jekyll-minifier**](https://github.com/digitalsparky/jekyll-minifier) gem. It collapses all whitespace into a single space.

If you disable that plugin, the feed generates as expected.

You should open an issue there about keeping preformatted whitespace. :+1:

**Comment by fabsenet** [comment]
jekyll-minifier was actually my first bet on the issue, but I disabled it to test it (at least I thought so) but removingit from the _config.yaml is not enough. I learned that now. I had to remove it from the gemfile as well. 

at least you are right, removing jekyll-minifier also removes the problem of missing newlines. thanks so far 👍
