### ISSUE TITLE
Use page.description for summary element, falling back to page.excerpt

### ISSUE THREAD

**Issue by mwaterfall** [jekyll/jekyll-feed#216]
[Jekyll SEO Tag](https://github.com/jekyll/jekyll-seo-tag) prioritises the `page.description` front matter value over `page.excerpt` ([see PR](https://github.com/jekyll/jekyll-seo-tag/commit/6dab82639ea393f93033efc5e3f5005e864de2b4)). It would be great to also have this for the feed item's `summary` element.

While `excerpt` typically contains a truncated snippet from the beginning of the post, `description` provides a place for the author to better summarise the content.

**Comment by benbalter** [comment]
That's a great idea. @mwaterfall would you be interested in submitting a pull request? I believe https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml#L68-L70 is the relevant code (Liquid template)
