### ISSUE TITLE
Feed is not generated for all pages

### ISSUE THREAD

**Issue by AshV** [jekyll/jekyll-feed#217]
Feed is not generated for all pages, in GitHub pages, am I missing something.
I have added plugins:  - jekyll-feed in my root _config.yml in my repo https://github.com/AshV/AshV.github.IO

Please suggest.

**Comment by DirtyF** [comment]
`jekyll-feed` only supports posts

**Comment by drewreece** [comment]
Is there a good reason not to override the feed.xml from the plugin? 

I copied "jekyll-feed/lib/jekyll-feed/feed.xml" to the project root & modified it to support the different collection type - alter the '{% assign posts = site.xxx…' iteration for starters also add front matter to cause it to be processed with 'layout: none'.

It's unclear to me what additional features the plugin adds so maybe it isn't required for use with other collections? Maybe there is a better way to allow the plugging to use other collections?

**Comment by pathawks** [comment]
@drewreece If this plugin does not suit your needs and using a custom `feed.xml` better fits the needs of your site, that's great :+1:

You will not get the benefits of future updates that come from using a Gem based theme, but it seems you have decided the trade-offs are worth it for your use case.
