### ISSUE TITLE
Using {{ site.url }} doesn't render the URL when compiled the second time with the --incremental option

### ISSUE THREAD

**Issue by Brar** [jekyll/jekyll-feed#219]
I ran into the same issue as #76 but this time it seems to be an incompatibility with the new `--incremental`  option from Jekyll 3.7.
It works as intended on the first run after modifying or touching a post but every run run afterwards exhibits the behavior described in #76

**Comment by DirtyF** [comment]
So this seems to be more of a Jekyll issue?

For the time being, I'd recommend to only use `--incremental` in development mode and run a full build for production.

**Comment by Brar** [comment]
> So this seems to be more of a Jekyll issue?

I have too little knowledge of the internals of the Jekyll plugin system to decide whose fault it is.

> For the time being, I'd recommend to only use --incremental in development mode and run a full build for production.

While I accept your recommendation I'd like to tell you that the `--incremental` option is especially useful for production scenarios as it leaves the timestamp of untouched files intact and by that supports differential deployments via fsync (or lftp in my case).
This is a huge gain if your site contains a lot of files that aren't regularly changed.
