### ISSUE TITLE
Gzip Option?

### ISSUE THREAD

**Issue by nebulousdog** [jekyll/jekyll-feed#221]
I was looking for how to turn on the gzip option mentioned [here](https://github.com/jekyll/jekyll-feed/issues/40#issuecomment-104046685) and [here](https://github.com/jekyll/jekyll-feed/issues/182#issuecomment-313964854).

The only location in the codebase I saw a mention was [here](https://github.com/jekyll/jekyll-feed/blob/master/spec/jekyll-feed_spec.rb#L209).

Thanks!!

**Comment by pathawks** [comment]
An HTTP server can Gzip requested resources. Services like Cloudfront or CloudFlare can sit between users and servers and do this automatically as well.

This is something that must be configured on the server, and is outside the scope of Jekyll or this plugin.

**Comment by nebulousdog** [comment]
ok thanks! makes sense.
