### ISSUE TITLE
bump / support typhoeus 1.0 series

### ISSUE THREAD

**Issue by decathorpe** [jekyll/jekyll-feed#231]
I'm currently working on getting jekyll to work on fedora again, and one of the things holding me back is the dependency on typhoeus ~> 0.7, whereas fedora already has typhoeus 1.0.2. Would it be possible to support the 1.0 series with the next release of jekyll-feed?

**Comment by benbalter** [comment]
I _think_ it should be compatible. If anyone would like to try updating the dependency, if tests pass, :+1: (it's only used for tests). One note, I'd suggest making it `>= 0.7`, `< 2.0` to avoid conflict with other (Jekyll) Gems that haven't yet upgraded.
