### ISSUE TITLE
Internationalization support for an RSS feed

### ISSUE THREAD

**Issue by azarrias** [jekyll/jekyll-feed#245]
Hi,

I'm trying to make a multilingual version of Hydeout, a Jekyll theme that uses your plugin for RSS:
https://github.com/azarrias/hydeout-multilingual
I'm just missing one feature and it is precisely this one, the RSS feed.

Is it possible to use your plugin to generate the RSS feed for a multilingual blog (according to the active page language)?

Thanks a lot!
Kind regards

**Comment by DirtyF** [comment]
Hi, 

You have to write a feed template for a multilingual Jekyll website at the moment, there's ongoing work for a better support of multiple languages in next major version of Jekyll, but for now jekyll-feed is unable to generate feeds according to languages set in config. You can generate feeds for categories though.
