### ISSUE TITLE
How to use excerpt

### ISSUE THREAD

**Issue by Mabbs** [jekyll/jekyll-feed#250]
I have no excerpt in my post YAML,but I want use excerpt and I want to strip HTML,How to do it?

**Comment by DirtyF** [comment]
By default, excerpt is the first paragraph of your post, the plugin already get it and strip html:

https://github.com/jekyll/jekyll-feed/blob/bf0b9c5721a0e41619920c62fa0cda4f4ff2ecf3/lib/jekyll-feed/feed.xml#L79-L81

**Comment by Mabbs** [comment]
Actually,The function isn't working,you can view my blog,it use the plugin

blog: https://mabbs.github.io/
repo:https://github.com/Mabbs/mabbs.github.io

**Comment by Mabbs** [comment]
@DirtyF Oh,sorry,I mean how to hide content?I just want to show excerpt.

**Comment by Mabbs** [comment]
Fine,I know is Atom,not RSS……
