### ISSUE TITLE
Any objection to makeing number_of_items configurable?

### ISSUE THREAD

**Issue by yyyc514** [jekyll/jekyll-feed#256]
```
{% for post in posts limit: 10 %}
```

Instead of the hard coded 10?

**Comment by pathawks** [comment]
Prior discussion on this matter:
#213
#193
#174
#107
#56

**Comment by yyyc514** [comment]
Hmm... Thanks.  Is there a canonical one I should add my thoughts to, or should I not even bother and just fork it for my own personal mods?

**Comment by pathawks** [comment]
The problem is that we are not willing to add another config option to support this feature.

If this is a feature you need, you will probably need to do something like fork the plugin, yes.

**Comment by yyyc514** [comment]
So noted.  Will do.  Thanks for being clear.
