### ISSUE TITLE
{% feed_meta %} ignores baseurl

### ISSUE THREAD

**Issue by Flyingmana** [jekyll/jekyll-feed#259]
when using a github page for a repository, not an user/organization, the page is placed in a subdirectory reflecting the repository name.

For this case, the feed_meta still points the feed to /feed.xml instead of {{ site.baseurl }}/feed.xml

**Comment by ashmaroli** [comment]
I see a `Gemfile` in the repository. So you may be able to check the plugin version in use via Bundler:
```
$ bundle show jekyll-feed
```
The version is at the end of the resulting string.

**Comment by Flyingmana** [comment]
`# bundle show jekyll-feed
/usr/local/bundle/gems/jekyll-feed-0.5.1
`

and I also found the reason, the docker container I used has a hardcoded version for github-pages

`gem "github-pages","78"`

after changing to a container with a current version it works as expected.
Sorry for the inconvenience.
