### ISSUE TITLE
Relative links in feed.xml

### ISSUE THREAD

**Issue by claudiuconstantin** [jekyll/jekyll-feed#260]
In my posts I use relative links to other posts:

`... yada, yada, here's [another](/random-post) article ...`

That renders just fine in my website, but the problem is with feed.xml - that link will prepend a contextual base_url of whatever the tool that displays it. For example in Mailchimp that link will look like `https://us6.campaign-archive.com/random-post`, which is incorrect.

The solution would probably be to make the relative links absolute at generation time or via a jekyll-feed setting. Any opinions on this?

**Comment by pathawks** [comment]
This should not be a problem, as the HTML content has [`xml:base` set](https://github.com/jekyll/jekyll-feed/blob/4372697f6b582199770b70fce91273cf579be661/lib/jekyll-feed/feed.xml#L53). If a feed reader doesn’t respect this, it is the reader that is broken.

Trying to replace the links through the plugin is a fool’s errand.

**Comment by claudiuconstantin** [comment]
[Here](https://claudiu.blog/feed.xml) you can see such „problematic” `feed.xml`. In the first `<content>` tag you can see that there's a `xml: base` attribute set up. Is that correct? Then in the actual content I have a relative `<a href="/munca-la-distanta">lucrez de acasă</a>` link. This link only works in the actual website, if you put that content somewhere else (feed in this example) it will automatically take a wrong base.

Probably this is more related to **Jekyll** itself and not jekyll-feed. I am sorry if this is the case. A potential solution is making that relative link absolute at generation time. Any suggestion would be appreciated.

**Comment by pathawks** [comment]
Because `<content>` has a `xml:base` attribute, and links inside that `<content>` block are assumed to be relative to that base.

```xml
<content type="html" xml:base="https://claudiu.blog/imbunatatiri">
    <p><a href="/about/">Link</a></p>
</content>
```

In this case, the link will resolve to `https://claudiu.blog/about/`. This is the intended behavior.

If a feed reader doesn't respect this, it is the reader that is broken.
