### ISSUE TITLE
Can jekyll-feed be disabled for development environment?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [jekyll/jekyll-feed#266]
The title is the question - Can jekyll-feed be disabled for development environment? So when I'm building locally, the feed doesn't get regenerated each time I build. But when I upload to GitHub Pages, then it'll get generated.

**Comment by mattr-** [comment]
There's not currently a way to disable a plugin on a per environment basis. You'd have to disable it  completely by removing it from your site and then make sure you leave that out that removal before committing and pushing.

**Comment by TheNewbieWoodworker** [comment]
Thanks! Someone on Jekyll Talk is helping me. I appreciate the response!

**Comment by claudiuconstantin** [comment]
@TheNewbieWoodworker, did you find a solution for this?

**Comment by ashmaroli** [comment]
@claudiuconstantin If you're not using the `github-pages` gem, you can try and build your site under `safe` mode: `bundle exec jekyll build --safe`.
Safe mode will load only those plugins that are listed under both `plugins:` and `whitelist:` in your config file.

**Comment by TheNewbieWoodworker** [comment]
@claudiuconstantin It turned out that this wasn't really slowing down my build much, it was something else.
