### ISSUE TITLE
What should we call this thing?

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-feed#27]
As we move to Atom via https://github.com/jekyll/jekyll-rss-feed/pull/24, does `jekyll-rss-feed` still make sense? `jekyll-atom-feed`? `jekyll-feed`? 

As @pathawks [noted](https://github.com/jekyll/jekyll-rss-feed/issues/2#issuecomment-101452969), "RSS is to feed as Kleenex is to facial tissue."

**Comment by sondr3** [comment]
I personally prefer `jekyll-feed` because I don't think it matters to most people whether you use RSS or Atom, just that it gives you a proper feed.

**Comment by benbalter** [comment]
I think that makes sense and makes things technology agnostic. As long as we talk about RSS in the readme, I think we should also still be discoverable.
