### ISSUE TITLE
[BUG]Code wont encode

### ISSUE THREAD

**Issue by Mabbs** [jekyll/jekyll-feed#270]
If you have XML keywords in back quotes, RSS will ERROR

**Comment by ashmaroli** [comment]
Please provide us with a proper example.
Also, do note that `jekyll-feed` generates Atom feeds.

**Comment by Mabbs** [comment]
Such as：
```
:xiang
echo  //special character
goto xiang
```
Oh, it's a special character that can't be parsed.

Link:https://mabbs.github.io/atom.xml

**Comment by Mabbs** [comment]
OK,I see. It's a special character fault.
