### ISSUE TITLE
Correct way to handle relative links in content?

### ISSUE THREAD

**Issue by WestonHanners** [jekyll/jekyll-feed#279]
I see that there are a couple issues already on this, but I don't think any of the explained this enough for me to understand, here is my issue

site url is `https://alloc-init.com`
feed is `https://alloc-init.com/feed`
posts are in `https://alloc-init.com/blog/...`
images are in `https://alloc-init.com/images/...`

My post content .md files refer to content by `images/someimage.jpg` and this works fine for viewing my website. 

I understand that the RSS reader is supposed to respect the xml:base, but in my case the base is being set to `https://alloc-init.com/blog/somearticle`

this causes feed links for images to resolve to 
`https://alloc-init.com/blog/images/someimage.jpg`

Is there something I should be changing to make this work correctly?

I am using Reeder for iPad to test and I am pretty sure it is a decent reader, also I am getting a ton of 404's in my http error log about this.

**Comment by ashmaroli** [comment]
@WestonHanners This is an interesting scenario. Is Jekyll being used to generate your entire site or just the "blog" part of it (apart from the feed)..?

**Comment by WestonHanners** [comment]
Entire site.

**Comment by ashmaroli** [comment]
Okay, and have you defined `baseurl` or `defaults` in your config file? If yes, can you post them?
Or if your site's source can be publicly accessed, can you post the url to the repo..?

**Comment by WestonHanners** [comment]
```
title: alloc-init
description: blog for @WestonHanners
email: admin@alloc-init.com
baseurl: ""
url: "https://alloc-init.com"
twitter_username: WestonHanners
github_username:  WestonHanners
encoding: utf-8
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

author:
  picture: images/me.jpeg
  twitter: WestonHanners

feed:
  path: feed

exclude: 
  - vendor
  - README.md
  - Gemfile*

pagination:
  enabled: true
  debug: true
  per_page: 5
  permalink: '/page/:num/'
  collection: 'posts'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

sass:
  sass_dir: _sass   
  style: compressed


permalink: /blog/:year.:month.:day
```

**Comment by ashmaroli** [comment]
Okay. Does commenting out the `permalink` config setting resolve the link issue..?

**Comment by ashmaroli** [comment]
If yes, you can maintain existing links to your posts with following configuration:
```yaml
# in config file

collections:
  posts:
    permalink: "/blog/:year.:month.:day"
    output: true
```

**Comment by WestonHanners** [comment]
it does not appear to have broken anything, but it also doesn't appear to have fixed anything.

**Comment by WestonHanners** [comment]
If you think it will help, I can add you to the repo to poke around, its on GitHub.

**Comment by WestonHanners** [comment]
thanks @ashmaroli, adding a leading `/` in my image links seems to have solved the issue.
