### ISSUE TITLE
Latest release 0.13.0 fails rspec tests

### ISSUE THREAD

**Issue by dleidert** [jekyll/jekyll-feed#292]
Hi,

the latest release fails several tests. Can you please check that? Here is a full build log:

https://salsa.debian.org/ruby-team/ruby-jekyll-feed/-/jobs/420659

Release 0.12.1 successfully completed the tests.

**Comment by parkr** [comment]
I'm not sure what's going on there. Our CI is able to run RSpec tests just fine.

I pulled `master`, ran `script/bootstrap` and `script/cibuild`.

**Comment by dleidert** [comment]
I found the culprit. Due to some dependency chain the system also had version 0.12.1 of jekyll-feed installed and used it instead of version 0.13.0. Therefor the resulting feed had unwanted content in it. Closing this report.

**Comment by parkr** [comment]
So glad you were able to find a resolution!
