### ISSUE TITLE
Generated feed does not validate on validator.w3c.org

### ISSUE THREAD

**Issue by Dovizu** [jekyll/jekyll-feed#298]
Discovered this issue while looking into [another issue](https://github.com/jekyll/jekyll-feed/issues/296). An example: https://validator.w3.org/feed/check.cgi?url=b-side.donny.io%2Ffeed.xml

**Comment by ashmaroli** [comment]
Based on the validation report, the errors seem to be because of `en_US` set as `lang` attribute.
This is actually defined in your config file.
Therefore, edit your config file to:
```yaml
_config.yml

lang: en
locale: en_US
```
Consequently, do edit the layouts and includes of your site to reflect the change above.

**Comment by Dovizu** [comment]
Great, edited the issue and now my feed validates. It was my mistake after all, thanks!
