### ISSUE TITLE
Adding content to end of feed items?

### ISSUE THREAD

**Issue by kevquirk** [jekyll/jekyll-feed#352]
Hey folks,

I really like the idea of having a "reply via email" link at the end of each item in my feed. I know I could simply add that link to the main content and it will be rendered in the feed, but I already have a button for this in my post layout.

Is it possible to inject such a link into the feed?

Thanks,

Kev

**Comment by ashmaroli** [comment]
@kevquirk It is currently not possible to add it via this plugin. However, you can always use your own `feed.xml` template by having one at your source directory.

**Comment by kevquirk** [comment]
Ok thanks.
