### ISSUE TITLE
why the chrome request for null layout?

### ISSUE THREAD

**Issue by rangercyh** [jekyll/jekyll-feed#366]
I have add a feed.xml in my site something like this
```xml
---
layout: null
---

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  ......
```

and then use chrome to open my site found it request for null and can not found, how can I solve it.

![QQ截图20220215191241](https://user-images.githubusercontent.com/1217541/154051443-95587ba1-4749-4f73-9a15-3e459a289d3c.png)
![QQ截图20220215191256](https://user-images.githubusercontent.com/1217541/154051460-e95a8940-4b42-4767-91a9-44eeaff32600.png)

**Comment by ashmaroli** [comment]
Perhaps some weird configuration.
If your repository is public, could you provide us with the link to it?

**Comment by rangercyh** [comment]
> Perhaps some weird configuration. If your repository is public, could you provide us with the link to it?

you may see at this

**Comment by rangercyh** [comment]
> Could not reproduce with the given repository, @rangercyh. Please provide exact steps you've followed.

Ok, I found maybe this is a chrome problem. When I use Edge to open my web site, it didn't request for the null page, but chrome did.
