### ISSUE TITLE
Why is my configuration no longer producing feed.xml?

### ISSUE THREAD

**Issue by dougbreaux** [jekyll/jekyll-feed#375]
https://github.com/dougbreaux/dougbreaux.github.io

**Comment by dougbreaux** [comment]
Help, please?

**Comment by parkr** [comment]
@dougbreaux Hey, we use Jekyll Talk (https://talk.jekyllrb.com) for support questions like this. Please refer your question to the community there! Thanks!

**Comment by dougbreaux** [comment]
Thanks. For reference (for myself): https://talk.jekyllrb.com/t/feed-xml-not-being-produced/7538

**Comment by dougbreaux** [comment]
Interestingly, found another random blog, that I could tell was GitHub Pages, with the same issue: https://uace.github.io/learning/feed.xml
