### ISSUE TITLE
Disable notification 'A new version of content is available.'

### ISSUE THREAD

**Issue by pronouncedJerry** [jekyll/jekyll-feed#380]
Is there a way to do so through the configuration options?

**Comment by parkr** [comment]
Hm, where are you seeing this notification?

**Comment by pronouncedJerry** [comment]
Right on the home (feed) page, for example https://chirpy.cotes.page

**Comment by ashmaroli** [comment]
@pronouncedJerry where exactly? Please post a screenshot.

**Comment by pronouncedJerry** [comment]
<img width="717" alt="Screenshot 2022-12-28 at 10 27 02 AM" src="https://user-images.githubusercontent.com/1200395/209834877-a8733a31-6996-4644-b3bb-dacdd8f90fd3.png">

**Comment by ashmaroli** [comment]
@pronouncedJerry This notification is a function of your feed reader / renderer.

Is this screenshot from Mozilla Firefox?

If you view the source code of your feed, you will see that the Feed generated by jekyll-feed does not contain any mention of a notification or the notification text.

If you have access to Google Chrome (the browser I am using on my devices), try accessing your feed url in that browser.

At this point, I would usually close this ticket stating that this is not a bug / actionable at our end. But in the current case, I will defer to your judgement.

**Comment by pronouncedJerry** [comment]
Alright. Thank you for looking into it. I'll look further into the browser options.
