### ISSUE TITLE
_config.yml name vs title

### ISSUE THREAD

**Issue by rayshan** [jekyll/jekyll-feed#47]
Currently `jekyll-feed` expects `name` in `_config.yml` as title of the website. Does it make more sense semantically to expect a `title` variable instead? Jekyll itself doesn't seem to care either way.

**Comment by pathawks** [comment]
It seems the [Jekyll site template](https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml#L2) prefers `title`, so that's probably what we should use as well.

**Comment by benbalter** [comment]
A quick GItHub code search suggests that [about 2.4M sites use "name"](https://github.com/search?l=yaml&q=%22name%3A%22+filename%3A_config.yml&ref=searchresults&type=Code&utf8=%E2%9C%93), while [only about 700,000 use `title`](https://github.com/search?l=yaml&q=%22title%3A%22+filename%3A_config.yml&ref=searchresults&type=Code&utf8=%E2%9C%93)

**Comment by rayshan** [comment]
Maybe people are using `name` for user / author name? Perhaps look for `title` first, if it doesn't exist, then look for `name`?

**Comment by sondr3** [comment]
Yet again I wish that Jekyll had a official way to organize your _config variables, haha, makes everything so much easier :smile:

**Comment by pathawks** [comment]
> Maybe people are using name for user / author name? Perhaps look for title first, if it doesn't exist, then look for name?

Taking just a quick look at the search results, yes, it looks like often the `name` matches the GitHub username.

**Comment by benbalter** [comment]
What do we think about `{{ site.title | fallback: site.name }}`? (If that'll even work?)

**Comment by pathawks** [comment]
That seems appropriate, though we'll probably have to do the ugly `if/else` like we do for `site.url` (but wouldn't a `fallback` be nice?)

**Comment by envygeeks** [comment]
We should add fallback to Jekyll as a default filter though that would only affect Jekyll 3 and this needs to support Jekyll 2.4+ but we should still add it, doing a search for liquid fallback shows tons of people offering it in their liquid installations.

**Comment by benbalter** [comment]
Looks like [it's in Jekyll > 2.0.0 as `default`](https://github.com/jekyll/jekyll/pull/1822).

**Comment by simonvanderveldt** [comment]
Just ran into this after adding this gem (nice that it's available on GitHub now :))
> It seems the Jekyll site template prefers title, so that's probably what we should use as well.

This was the reason I was using `site.title`, I guess it will be for most people starting from scratch.

The suggested `site.title` + fallback to `site.name` sounds good.
(I've switched to `site.name` for now, but would prefer `site.title`)

**Comment by ilg-ul** [comment]
English is not my first language, but semantically I think it is more natural for sites to have names  (similarly to libraries, shops, etc) and pages to have titles (similarly to books, articles, etc).

**Comment by pathawks** [comment]
I believe that #72 closes this issue
