### ISSUE TITLE
Liquid syntax error in jekyll 3.0

### ISSUE THREAD

**Issue by rayshan** [jekyll/jekyll-feed#48]
`jekyll 3.0.0.pre.beta5`

While trying to serve:

`  Liquid Exception: Liquid syntax error: Expected end_of_string but found pipe in "post in site.posts | limit: 10" in feed.xml`

Not sure why liquid is processing `feed.xml`, I thought anything not prefixed with `_` won't get processed.

**Comment by pathawks** [comment]
It seems [we need to omit the pipe](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#for-loops).
