### ISSUE TITLE
`<summary>` is always blank on jekyllrb.com

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll-feed#52]
My hunch is that `if page.excerpt` when `page.excerpt` is `""` is still truthy. We should make sure it's also not empty.

![screen shot 2015-05-28 at 10 39 09 am](https://cloud.githubusercontent.com/assets/237985/7866661/d3ace13c-0525-11e5-97b5-018ac461ae9b.png)

**Comment by envygeeks** [comment]
I wonder how you would address that, should we have Jekyll default to always providing an excerpt? I don't know how hard it would be (and if it does turn out to be hard then it'll be high-time I implement Liquid Drops in Jekyll and ship the pull.)
