### ISSUE TITLE
make the plugin usable with markup other than markdown

### ISSUE THREAD

**Issue by tsachev** [jekyll/jekyll-feed#61]
Currently the plugin will ```markdownify``` the content from posts, but I am trying to use it with jekyll-asciidoc, and the content is not in html format.

**Comment by parkr** [comment]
Instead of rendering and writing ourselves, build the feed page and add to site.pages. Ensure sitemap: false and it should work well! Maybe we could add a site.generated_pages to Jekyll core to eliminate the modification to user data

**Comment by pathawks** [comment]
This should be fixed by #73
