### ISSUE TITLE
double // in feed.xml

### ISSUE THREAD

**Issue by dentarg** [jekyll/jekyll-feed#63]
with this in my `_config.yml`

```yaml
baseurl:      /
url:          https://my.site.com
```

feed.xml will render as

```xml
...

<link href="https://my.site.com//" rel="alternate" type="text/html" />

...

<link href="https://my.site.com//2015/07/01/foo-bar/" rel="alternate" type="text/html" title="Foo Bar" />

...

<id>https://my.site.com//2015/07/01/foo-bar</id>
<content type="html" xml:base="https://my.site.com//2015/07/01/foo-bar/">
```

I could change the configuration to `baseurl: ""`, but wouldn't that make the `{{ site.baseurl }}` rather useless? You would always have to use it like `<a href="{{ site.baseurl }}/">`. But maybe that's the Jekyll way?

**Comment by pathawks** [comment]
> But maybe that's the Jekyll way?

Yup.

**Comment by parkr** [comment]
`baseurl: ""` and `baseurl: "/"` _should_ be handled identically by Jekyll. Perhaps `prepend` is just too simple for this complicated solution of path joining.

That said, I know `baseurl` is meant to be either `""` or `"/some-base-path"`, i.e. _never_ ending in a `/`. So maybe this is a case of (mis)use gone awry yet again.

**Comment by dentarg** [comment]
Thanks for clarifying. I've made the switch to `baseurl: ""` and `{{ site.baseurl }}/` for our Jekyll setup.

I let you decide if you want to close or leave this issue open.

**Comment by parkr** [comment]
Let's close it. Thanks for reporting! Hopefully this conversation will help others in the future.

**Comment by AuyaJackie** [comment]
Hello!

Im a green student, Im already try more time also lose!

azure ...Im very thank them help me upload the code my HitGub....but Im still can build up a website builder!

Can you tell me , have the most of simple action to install thw websitebulder😭😭😭😭😭

傳送自 iOS 版 myMail


2015年9月12日 星期六 上午12:49 +0800 寄件人 Ben Balter  <notifications@github.com>:
