### ISSUE TITLE
Gem won't compiling on Cygwin

### ISSUE THREAD

**Issue by ryayon** [jekyll/jekyll-feed#65]
Hi,

  I can't install the gem anymore on my up-to-date cygwin.

  Actually, nokogiri is the cause.

  The requested nokogiri version is the `>1.6` and it will try to install the version `1.6.6.2`which won't install on Cygwin.

  After some searchs, I found out it is a known bug (https://groups.google.com/forum/#!topic/nokogiri-talk/BigaPrf2AwE).

  I can confirm I have been able to install the version `1.6.7.rc3`.

  Please update the requested version to the 1.6.7 final release as soon as you can.

Regards and good job for the rest,
Rudy

**Comment by nicholasjackson827** [comment]
I'm assuming you're using Windows? What version of Ruby are you using?

**Comment by ryayon** [comment]
Hi,

  yes, I am on Cygwin (windows).

  The ruby version is:

```bash
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-cygwin]
```

Regards

**Comment by excel-tricks** [comment]
Nokogiri doesn't support Ruby 2.2 on Windows.

See [this issue](https://github.com/sparklemotion/nokogiri/issues/1256) for details.

**Comment by benbalter** [comment]
> Nokogiri doesn't support Ruby 2.2 on Windows.

Closing as an upstream issue. Downgrading to Ruby 2.1 should allow the Gem to compile.
