### ISSUE TITLE
Handling of whitespace in title / excerpt

### ISSUE THREAD

**Issue by maul-esel** [jekyll/jekyll-feed#66]
## Problem
The current `feed.xml` strips newlines from the title and excerpt. However, that leaves no space between the last word of a line and the first word of the next line.

## Example
The markdown
```
This is some
text
```

leads to `This is sometext`.

## Suggestion
Replace `strip_newlines` with `replace: '\n', ' '`.

**Update:** or rather `replace: '\r\n', ' ' | replace: '\n', ' '`.

**Comment by benbalter** [comment]
> Replace `strip_newlines` with `replace: '\n', ' '`.

Is there an example of when we wouldn't want `strip_newlines` to behave that way?

**Comment by maul-esel** [comment]
I'm not sure I understand the question. Are you suggesting to make it the default behaviour of `strip_newlines` to insert spaces?

**Comment by benbalter** [comment]
> Are you suggesting to make it the default behaviour of `strip_newlines` to insert spaces?

Yep. Can you think of when a user *wouldn't* want that behavior? I assumed that's how it worked.

**Comment by maul-esel** [comment]
I can't think of one, but who knows...

Also, overriding `strip_newlines` *in jekyll* would cause the same Liquid markup used with jekyll to behave differently than when used somewhere else – that might be quite confusing. The alternative would be to try patching it upstream.

**Comment by pathawks** [comment]
I would call this a `strip_newlines` issue.

**Comment by maul-esel** [comment]
I disagree. `strip_newlines` is supposed to remove newlines, and that's exactly what it does, nothing more and nothing less.

**Comment by parkr** [comment]
We'd want a `replace: '\n', ' '` situation.

**Comment by zhangzheng08331** [comment]
Hello!Please give an example if we wouldn't want strip_newlines to behave that way?

**Comment by pathawks** [comment]
This should be fixed by #67
