### ISSUE TITLE
Unexpanded links in <content>...</content> elements

### ISSUE THREAD

**Issue by ilg-ul** [jekyll/jekyll-feed#69]
I just installed this nice plug-in to my site (http://gnuarmeclipse.github.io/feed.xml) and when I viewed the articles in **feedly** I noticed the images are not ok.

checking the xml, I discovered something like this:

`&lt;p&gt;&lt;img src=&quot;%7B%7B%20site.baseurl%20%7D%7D/assets/images/2015/github-gae-header.png&quot; alt=&quot;GNU ARM Eclipse GitHub Home&quot;&gt;&lt;/p&gt;
`

obviously the `{{ site.baseurl }}`was not expanded properly in the `<content>...</content>` elements. I guess the same happens in the `<summary>...</summary>` elements too, but I can't prove it, my site has simple summary paragraphs.

would it be possible to expand the variables when generating the `feed.xml` file, and produce a functional page?

**Comment by parkr** [comment]
Similar to #58 and #61. We have a thought in mind for a solution but it introduces another problem.

**Comment by ilg-ul** [comment]
I guess that the problems are related, but I'm not sure they are exactly the same problem. Perhaps trying to identify each individual problem and then address them one by one would help.

In this case just performing the substitution before escaping the html chars might be enough.

**Comment by parkr** [comment]
They are all symptoms to the same issue: the feed is not fully rendered because it's constituent pieces are not rendered (e.g. posts)

**Comment by ilg-ul** [comment]
Then probably it would be safer to revert to RSS and use only the excerpts, which, at least in my case, are simply enough to be correct.

**Comment by leo** [comment]
Please neither revert to RSS, nor only show excerpts. It's important that we'll find a solution for this problem without cutting off a piece of the awesomeness of this plugin.

**Comment by ilg-ul** [comment]
If there is anything I can do to help you fix the problem, please let me know. Unfortunately my experience with Jekyll/Ruby is not enough to take an active path, but I can do some testing, if useful.

**Comment by pathawks** [comment]
This should be fixed by #73
