### ISSUE TITLE
Validator warning: `Missing feed element: title`

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-feed#71]
So it seems that is missing. Would it be possible to add a new config for that?

**Comment by parkr** [comment]
How can we approach this without adding a new config?

Also, can you please provide a link to the resource which showed you this error?

Thanks!

**Comment by XhmikosR** [comment]
@parkr: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmpc-hc.org%2Frss.xml

I guess one could use maybe the description or something but still won't be perfect. For example, I used "The latest news for the MPC-hC project" before I switched to jekyll-feed.

**Comment by parkr** [comment]
Sites made with `jekyll new` have a `site.title` and `site.description`. @benbalter, what do you think? I'm leaning towards `site.title`.

**Comment by benbalter** [comment]
For the feed title? Yes, [it currently uses `site.name`](https://github.com/jekyll/jekyll-feed/blob/master/lib/feed.xml#L14-L16), but I believe it should be `site.title`which mirrors `post.title` (potentially with fallback to `site.name`).
