### ISSUE TITLE
add @parkr as gem owner so he can push new versions

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll-feed#74]
@benbalter, this one's for you.

Could you add me as a gem owner for this gem? https://rubygems.org/gems/jekyll-feed

My personal gmail address (which I believe you have) will activate.

```bash
$ gem owner jekyll-feed --add <parkr's email>
```

Thank you!

**Comment by benbalter** [comment]
You should now have access.

**Comment by parkr** [comment]
I do! Praise you, @benbalter. :heart: :sparkles: :pray:
