### ISSUE TITLE
Omitting `jekyll` gem in `_config.yml` makes liquid markup unexpanded.

### ISSUE THREAD

**Issue by arkfps** [jekyll/jekyll-feed#78]
This works
```ruby
gems:
  - jekyll 
  - jekyll-feed
```
while the following does not
```ruby
gems:
  - jekyll-feed
```

**Comment by parkr** [comment]
Are you using a gemfile? Are you executing Jekyll with `bundle exec`?

**Comment by arkfps** [comment]
Yes to both.

**Comment by arkfps** [comment]
Apparently this is unrelated to `jekyll` gem. The cause is Jekyll 3.x incremental build feature. Everything works fine after building from scratch, but subsequent rebuild with `incremental` flag breaks liquid expansion.
