### ISSUE TITLE
Incorrect `link[href]` value if baseurl is provided in _config.yml

### ISSUE THREAD

**Issue by oncletom** [jekyll/jekyll-feed#79]
Given the following `_config.yml` file content:

```yml
baseurl: /blog
feed:
  path: feed.xml
```

The liquid tag `{% feed_meta %}` renders:

```
<link type="application/atom+xml" rel="alternate" href="feed.xml" title="..." />
```

(instead of)

```
<link type="application/atom+xml" rel="alternate" href="/blog/feed.xml" title="..." />
```

Whereas the feed is properly generated at `localhost:4000/blog/feed.xml` (and not at localhost:4000/feed.xml`.

If I change the value of the `path` to `blog/feed.xml`, the `link[href]` value is correct but then the feed content is not rendered at the given URL.

Is there anything special to do? I thought we'd have followed the README correctly.

Thanks :-)

refs sudweb/blog#10

**Comment by DirtyF** [comment]
It looks like the link tag is not generated with `baseurl` https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed.rb#L31

as in the `feed.xml` file it is taken into account : https://github.com/jekyll/jekyll-feed/blob/master/lib/feed.xml#L3

but I'm sure @parkr or @benbalter have a good explanation for this.

**Comment by DirtyF** [comment]
@pathawks thanks for the fix
