### ISSUE TITLE
feed_meta won’t take baseurl into account

### ISSUE THREAD

**Issue by exalted** [jekyll/jekyll-feed#84]
On http://workinprogress.github.io/website/ (which is built & served by GitHub pages) I use `{% feed_meta %}`, however that doesn't seem to take `baseurl` setting into account.

Generated URL is http://workinprogress.github.io/feed.xml rather than http://workinprogress.github.io/website/feed.xml **(note the subpath `/website`)**.

Is this the expected behaviour? What am I missing please?

:beers:

**Comment by exalted** [comment]
Addendum:

```
# config.yml
baseurl: "/website"
url: "https://workinprogress.github.io"
```

**Comment by benbalter** [comment]
[Here's](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed.rb#L29-L35) the relevant logic. It should, but I suspect it's looking to `site.github.url`.

@exalted what's the value of `site.github.url` for your site in production? (You can add `<!-- {{ site.github.url }} -->` to a page to output it as an HTML comment (and view source to see it).

**Comment by exalted** [comment]
@benbalter thanks for the feedback. According to [docs](https://help.github.com/articles/repository-metadata-on-github-pages/) `site.github.url` (for example) is going to be http://username.github.io/example; so in my case it should be http://workinprogress.github.io/website and indeed it is.

However shouldn't that piece of logic you pointed out make it so `site.url` having a higher priority than `site.github.url`?

Jekyll docs [suggest](http://jekyllrb.com/docs/github-pages/#project-page-url-structure):

> In `_config.yml`, set the `baseurl` option to `/project-name` – note the leading slash and the absence of a trailing slash.

... but it doesn't mention removing `site.url`.

Any ideas?

P.S.: https://github.com/jekyll/jekyll-sitemap/issues/47 feels like a similar problem to me.

**Comment by exalted** [comment]
I guess https://github.com/jekyll/jekyll-feed/commit/3321d8bae50101a819fac942888269d333c8027a might fix this issue, but it's not released yet? Not sure.

**Comment by benbalter** [comment]
Ahh that's exactly it (and why I was confused). Look for a fix soon.

**Comment by exalted** [comment]
@benbalter apparently https://github.com/jekyll/jekyll-feed/pull/80 is merged already; waiting to be released...
