### ISSUE TITLE
Excerpt Only feed

### ISSUE THREAD

**Issue by ickc** [jekyll/jekyll-feed#88]
I suggest to have an option in config such that the rss feed includes excerpt only but not content.
Please pardon me if this feature is already here. I couldn't see it in the readme.

**Comment by benbalter** [comment]
@ickc could you explain the use case for when you'd use that?

**Comment by ickc** [comment]
An example of the feeds I have seen that are like this: http://appleinsider.com/appleinsider.rss

**Comment by pathawks** [comment]
What benefit does this provide?

**Comment by ickc** [comment]
Traffic to the site

**Comment by markkimsal** [comment]
+1 for this feature.  I was surprised when I found out it included the entire article content in the feed.

**Comment by neoascetic** [comment]
+1

**Comment by pathawks** [comment]
Please, rather than posting a generic `+1`, either use [GitHub’s emoji reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to express general support for something, or post a detailed comment explaining why you would like to see a feature implemented. :star:

**Comment by benbalter** [comment]
It seems to me, the benefit to having an excerpt would be to force the reader to visit your site, creating a page view, which could be used to serve ads (or, e.g., in the case of e.g. a marketing blog, a potential conversion). Is there any other benefit to not providing the full content?

**Comment by ickc** [comment]
Size might be another consideration. For really long article, an excerpt would give the readers a choice to read the full article after the introduction/excerpt. Especially if a lot of photos are involved, inlcuding only one photo in the excerpt will help people minimize their data expenses.

In a sense people can configure their RSS reader to pre-load photos or not. But some might want the convenience to pre-load everything. Having them to pre-load a long articles including lot of photos will be a penalty to them, and potentially unsubscribe the feed.

Another factor to consider is typography. A site I subscribed to recently gone through a major reconstruction. Their website has used some very beautiful design and typography, that in an RSS reader would look pretty ugly (e.g. they use a lot of `<mark>` element to highlight the key sentences for the reader in long articles, and in their CSS it is marked will a gray background. But the RSS reader using default CSS will render them bright yellow, which is much more unpleasant than the original design.). In that case the excerpt help the reader to pre-load a very small excerpt and decide if they will dive into the full site or not.

All in all, the trend now for many RSSs is to provide a short excerpt, and there could be many use case. But I think the one who control the content should have the choice. In Jekyll such a choice exists in the way that a custom RSS feed can be written (that's what I have in the past). But I think having such official plugins is to simplify the whole process, rather than reinventing it again and again. And a simple "toggle" of having excerpt or not shouldn't overcomplicate the plugin (which I understand the official solutions usually want to avoid).
