### ISSUE TITLE
duplicate entries in RSS feed from jekyll website

### ISSUE THREAD

**Issue by jangorecki** [jekyll/jekyll-feed#91]
Hi,
Could anybody point me to documentation, or at least discussion about the case, when jekyll will re-create all the RSS feeds resulting into duplicate on the reader side.
It is in some way a pain for blogs which are being aggregated with blog aggregators.
I've run into such issue very recently, I'm almost sure the below change in `gems` section was the reason ([related commit]
(https://github.com/jangorecki/jangorecki.github.io/commit/6b7a24525c3ec12f222d0b32249834b1076f723a)).

before
```
gems:
  - jemoji
  - jekyll-sitemap
```
after
```
gems:
  - jekyll-feed
  - jekyll-sitemap
```

It could be also changing `http` into `https` in `url` jekyll variable.

My RSS feeds of previously released (and already broadcasted via rss) blog posts were re-broadcasted.  
**I would like to precisely know how to avoid re-distribution of my old blog posts in RSS in case of future commits to blog**, so canonical docs would be the best.
Thanks in advance.

**Comment by jangorecki** [comment]
is this project still maintained?

**Comment by pathawks** [comment]
Can you give a bit more detail about your problem? I don’t really understand what you are asking.

How were you creating your feed previously? Do you have a before and after?

**Comment by jangorecki** [comment]
@pathawks I'm asking about strict rules of broadcasting (and so also potentially unwanted re-broadcasting) blog posts via rss.

I created feed as `feed.xml` file (based on famous jekyll-now repo).
```
---
layout: null
---
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{{ site.name | xml_escape }}</title>
    <description>{{ site.description | xml_escape }}</description>
    <link>{{ site.url }}</link>
    <atom:link href="{{ site.url }}/feed.xml" rel="self" type="application/rss+xml" />
    {% for post in site.posts limit:10 %}
      <item>
        <title>{{ post.title | xml_escape }}</title>
        <description>{{ post.content | xml_escape }}</description>
        <pubDate>{{ post.date | date: "%a, %d %b %Y %H:%M:%S %z" }}</pubDate>
        <link>{{ site.url }}{{ post.url }}</link>
        <guid isPermaLink="true">{{ site.url }}{{ post.url }}</guid>
      </item>
    {% endfor %}
  </channel>
</rss>
```
All my posts have been re-broadcasted after a commit [6b7a245](https://github.com/jangorecki/jangorecki.github.io/commit/6b7a24525c3ec12f222d0b32249834b1076f723a).

I believe one of the following changes in `_config.yml` was the reason.

before:
```
url: https://jangorecki.github.io

gems:
  - jemoji
  - jekyll-sitemap
```

after:
```
url: http://jangorecki.github.io

gems:
  - jekyll-feed
  - jekyll-sitemap
```

Exact before and after available in linked commit.

**Comment by pathawks** [comment]
Yes, changing the `site.url` from http to https would cause the ID for _all_ the posts to change. As such, feed readers would believe the feed is full of new posts.

This shouldn’t happen again, so long as you do not change `site.url`

**Comment by jangorecki** [comment]
@pathawks OK, thanks for info. BTW. I changed `url` not the `site.url` in `_config.yml`, not sure if that matters.  Are there any other cases than may lead to feeds duplication or just this one?
