### ISSUE TITLE
Exclude Drafts from feed

### ISSUE THREAD

**Issue by jeremiemartinez** [jekyll/jekyll-feed#94]
Hi there,

What do you think about filtering future posts from the `feed.xml` ?

To give you some context, most of the time I write a new article, I publish it with a future date, it is not listed and I send direct link to friends for proof reading. My problem is that even if my article has a future date, it still appears in the `feed.xml`...

Would you be willing to accept a PR if I work on it ? Is there any other way to filter posts appearing in the `feed.xml` ?

Thanks,

**Comment by pathawks** [comment]
I have also published a post “publically” for the purpose of sending it to somebody to proofread.

I’m not sure if future date is the way to do this, seems like that could lead to some trouble if time zones or something caused Jekyll to improperly exclude a new post from the feed.

Perhaps a way to explicitly exclude a post from the feed, similar to `sitemap: false`?

**Comment by jeremiemartinez** [comment]
So we could have something like: `feed: false` that could be added to the frontmatter of each post and then filtered in the for loop in `feed.xml`. Is that what you mean ? It would also be a good solution since I understand your concerns about time zones.

**Comment by pathawks** [comment]
> So we could have something like: `feed: false` that could be added to the frontmatter of each post and then filtered in the for loop in `feed.xml`. Is that what you mean ?

:+1:

**Comment by benbalter** [comment]
@jeremiemartinez how do you prevent future posts from appearing in your site's human-readable index? 

I'm wondering if rather than have the user specify the feature they want ("don't include this in the sitemap", "don't include this in the feed"), the user should expose intend ("this shouldn't be public"), and the two plugins should respond accordingly.

**Comment by jeremiemartinez** [comment]
@benbalter Well, my approach is very similar that the one advised by @pathawks. However, don't judge me, this is not the best code I wrote...

First, I add `future: true` to my `_config.yml`. 
Then, I declare in the frontmatter: `public: 1`
Finally, in my `index.html`, I loop and filter:
```
{% for post in paginator.posts %}
   {% if post.public != 1  %}
        […]
   {% endif %}
 {% endfor %}
```

Your idea about a public flag that could be used for every plugin is great but it would require to directly modify jekyll to expose such an API I guess :/

**Comment by pathawks** [comment]
Jekyll has a **Drafts**  feature already: is there any way in Liquid to detect if a post is a draft?

I can think of multiple reasons why a public page/post should be excluded from a sitemap (even if not excluded from the public view of a site), but the *only* reason I can think of to exclude a post from the site feed is if it is just a draft snd not yet “public.”

I am just trying to think through this aloud.

**Comment by jeremiemartinez** [comment]
Draft would be a good solution but it seems that Github does not deploy drafts so I cannot ask friends for proofreading unfortunately.

**Comment by jeremiemartinez** [comment]
Sorry I am completely wrong with my last comment. Just need to add `show_drafts` flag to my `_config.yml`. So knowing if a post is a draft matches our need.

**Comment by pathawks** [comment]
I wasn’t thinking about GitHub Pages. That makes things a bit trickier, doesn’t it.

**Comment by jeremiemartinez** [comment]
Well, as I corrected in my previous comment, with `show_drafts` Github Pages does work.

I look for a way to know whether a post is an draft or not. We can with something like:
```
{% if post.draft != true %}
```

What do you think about this solution?

**Comment by KingScooty** [comment]
```ruby
{% for post in site.posts %}
    {% unless post.draft %}
    {% endunless %}
{% endfor %}
```

**Comment by jeremiemartinez** [comment]
Fixed by #95.

**Comment by jeremiemartinez** [comment]
Hey guys, any idea about a release date ? I would love to include this change in my current project!

**Comment by parkr** [comment]
@jeremiemartinez v0.5.0 was just released. 😄

**Comment by jeremiemartinez** [comment]
Great news ! Thanks :)
