### ISSUE TITLE
Somethings broken with the liquid `feed_meta`

### ISSUE THREAD

**Issue by zbeekman** [jekyll/jekyll-feed#96]
Might this have to do with the recent jekyll upgrade?

If I build as github does with `bundle exec jekyll build --safe` then I get the following error:

```
Liquid Exception: Liquid syntax error (line 22): Unknown tag 'feed_meta' in _includes/head.html, included in _layouts/default.html
jekyll 3.0.3 | Error:  Liquid syntax error (line 22): Unknown tag 'feed_meta'
```

However, if I don't pass `--safe` then everything works as expected.

line 22 is just `{% feed_meta %}` inside `<head>` in `default.html`.

I use the github-pages gem, here is my gem file:

```
source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']
gem 'jekyll-feed'
```

and I have this in `_config.yml`:

```
# GH-pages supported plugins
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
```

**Comment by zbeekman** [comment]
Note: I updated the original comment to reflect that there are no problems unless `--safe` is passed to `jekyll build`. The discussion of github pages supported jekyll extensions explicitly mentions injecting the meta tag for the feed via `{% feed_meta %}` so I expected this to work on gh-pages.

**Comment by parkr** [comment]
Remove `--safe`. We're working through the kinks of getting Jekyll to work well locally in "GitHub Pages mode". https://github.com/github/pages-gem/issues/200

**Comment by zbeekman** [comment]
Hi @parkr, thanks for the response. Yes, I am aware that I can remove the `--safe` flag locally, but if I use the automated github-pages build, then then I get an email notifying me that the build failed and the site was not deployed. I just wanted to make sure that this was reported somewhere. Thanks!

**Comment by parkr** [comment]
@zbeekman Let me know if you write into support@github.com and I can take a look at your repo to see what's happening. Removing `--safe` should help; `--safe` doesn't change that much.

**Comment by zbeekman** [comment]
> Removing --safe should help; --safe doesn't change that much.

Yes I agree, but **Github pages always adds `--safe`** when building your repo: 

https://github.com/zbeekman/zbeekman.github.io

**Comment by parkr** [comment]
@zbeekman Yes, it does but it also has a number of configuration options that it sets, such as whitelist, that allows certain plugins to be required. Subscribe to https://github.com/github/pages-gem/issues/200 and you will be notified once it is fully-functional. Right now, `--safe` and plugins aren't compatible outside of GitHub Pages, so don't use `--safe` for now.

**Comment by zbeekman** [comment]
OK, I think we're talking past each other here. I'm pretty sure I'm not using --safe and the liquid expansion is failing when built by Github. I'll try to make a demo repository to show you.

**Comment by parkr** [comment]
@zbeekman The error from 4 days ago is not because of `jekyll-feed`. It's a Sass issue:

```
 Liquid Exception: Liquid error (line 45): $color: 2863a6 is not a color for `rgba' on line 448 in _includes/head.html, included in _layouts/default.html
Liquid error (line 45): $color: 2863a6 is not a color for `rgba' on line 448
```
