### ISSUE TITLE
Includes not parsed/removed

### ISSUE THREAD

**Issue by maciejlew** [jekyll/jekyll-feed#97]
I use includes in my blog posts. It seems like they are not parsed while generating feeds. I can see something like "{% include acronyms.md %}" in messages from my blog. How can I remove includes from feeds messages? Is there any option?

**Comment by parkr** [comment]
@maciejlew It sounds like your file is not being rendered properly. Your includes should be properly rendered. Ensure you have [YAML front matter](http://jekyllrb.com/docs/frontmatter/) at the top of the offending posts and that there is no BOM preceding the first three lines, nor any trailing spaces after these lines. That should fix your issue. If you provide a link to the source of your blog, I can also take a look. Hope this helps!

**Comment by parkr** [comment]
Also, make sure you are using v0.4.0: https://github.com/jekyll/jekyll-feed/releases/tag/v0.4.0

**Comment by maciejlew** [comment]
GitHub Pages uses v0.3.0, maybe that is the problem.

Here is sample post: 
https://github.com/maciejlew/maciejlew.github.io/blob/master/_posts/2016-02-13-konfiguracja-serwera-ci-dla-lms.md

Now I see includes are not parsed at GitHub preview as well.

Here is that post parsed: 
http://lion.net.pl/2016/02/13/konfiguracja-serwera-ci-dla-lms.html


W dniu 15.02.2016 o 20:42, Parker Moore pisze:
